### ISSUE TITLE
How are we handling GDPR here?

### ISSUE THREAD

**Issue by seansan** [magepal/magento1-google-tag-manager#21]
How are we handling GDPR here?

This data is no longer allowed to be sent and shared (without prior optin consent)

customer.isLoggedIn
customer.id
customer.groupId

**Comment by srenon** [comment]
@seansan ... I have zero/little knowledge in these areas, especially EU laws.

Base on my quick review of https://www.csoonline.com/article/3202771/data-protection/general-data-protection-regulation-gdpr-requirements-deadlines-and-facts.html

Since customer.isLoggedIn, customer.id, customer.groupId is all information that is either known or belongs to store owner and do "not fall" into any of the area listed in the link about. Does this violate GDPR?

What would be your recommendation (adding a system config to enable/disable it)?

**Comment by seansan** [comment]
​​
let me push some updates in a sec

**Comment by srenon** [comment]
@seansan ... Thanks
